defaults:
    - task: cls
    - model: point_transformer
    - task_model: ${defaults.0.task}-${defaults.1.model}

hydra:
  run:
    dir: outputs

gpus:
    - 0

optimizer: ???

task_model: ???

model: ???

distrib_backend: dp
